export const CHANGE_TAB = 'CHANGE_TAB';

// Data Actions
export const ADD_PLOT = 'ADD_PLOT';
export const LOAD_PLOTS = 'LOAD_PLOTS';
export const LOAD_PLOTS_DONE = 'LOAD_PLOTS_DONE';
export const LIST_PLOT = 'LIST_PLOT';
export const PLOT_LISTED = 'PLOT_LISTED';

// Grid Actions
export const HOVER_OVER_PLOT = 'HOVER_OVER_PLOT';
export const ENTER_BUY_MODE = 'ENTER_BUY_MODE';
export const START_DRAGGING_RECT = 'START_DRAGGING_RECT';
export const STOP_DRAGGING_RECT = 'STOP_DRAGGING_RECT';
export const RESIZE_DRAGGING_RECT = 'RESIZE_DRAGGING_RECT';
export const SHOW_PURCHASE_DIALOG = 'SHOW_PURCHASE_DIALOG';
export const HIDE_PURCHASE_DIALOG = 'HIDE_PURCHASE_DIALOG';
