export const CHANGE_TAB = 'CHANGE_TAB';

// Data Actions
export const ADD_PLOT = 'ADD_PLOT';
export const LOAD_PLOTS = 'LOAD_PLOTS';
export const LOAD_PLOTS_DONE = 'LOAD_PLOTS_DONE';
export const LIST_PLOT = 'LIST_PLOT';
export const PLOT_LISTED = 'PLOT_LISTED';

// Grid Actions
export const HOVER_OVER_PLOT = 'HOVER_OVER_PLOT';
export const ENTER_BUY_MODE = 'ENTER_BUY_MODE';
export const START_DRAGGING_RECT = 'START_DRAGGING_RECT';
export const STOP_DRAGGING_RECT = 'STOP_DRAGGING_RECT';
export const RESIZE_DRAGGING_RECT = 'RESIZE_DRAGGING_RECT';
export const SHOW_PURCHASE_DIALOG = 'SHOW_PURCHASE_DIALOG';
export const HIDE_PURCHASE_DIALOG = 'HIDE_PURCHASE_DIALOG';
export const CHANGE_ZOOM = 'CHANGE_ZOOM';

// Account Actions
export const UPDATE_METAMASK_STATE = 'UPDATE_METAMASK_STATE';

// Purchase Actions
export const TOGGLE_PURCHASE_FLOW = 'TOGGLE_PURCHASE_FLOW';
export const PURCHASE_IMAGE_SELECTED = 'PURCHASE_IMAGE_SELECTED';
export const START_TRANSFORM_RECT = 'START_TRANSFORM_RECT';
export const STOP_TRANSFORM_RECT = 'STOP_TRANSFORM_RECT';
export const TRANSFORM_RECT_TO_PURCHASE = 'TRANSFORM_RECT_TO_PURCHASE';
export const COMPLETE_PURCHASE_STEP = 'COMPLETE_PURCHASE_STEP';
export const GO_TO_PURCHASE_STEP = 'GO_TO_PURCHASE_STEP';
export const CHANGE_PLOT_WEBSITE = 'CHANGE_PLOT_WEBSITE';
export const CHANGE_PLOT_BUYOUT = 'CHANGE_PLOT_BUYOUT';
export const CHANGE_BUYOUT_ENABLED = 'CHANGE_BUYOUT_ENABLED';